name: Linters
on:
  pull_request:
    branches:
      - master

jobs:
  commitsar:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Check compliance with conventional commits
        uses: commitsar-app/commitsar@v0.6.6
